// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svhhrejbyfritxuipxnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2aGhyZWpieWZyaXR4dWlweG5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyODc5MzksImV4cCI6MjA2MDg2MzkzOX0.6uom8Q46ZHHL3KWsA8PT6U9Hg9RHGRqA2bIQwEC5aM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);